/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.PrestamosController;
import Controllers.PrincipalController;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author ivand
 */
public class EdicionDePrestamosView extends javax.swing.JPanel {

    /**
     * Creates new form EdicionDePrestamosView
     */
    public EdicionDePrestamosView() {
        initComponents();
        
        initStyle();
    }

    private void initStyle(){
        nombreLabel.putClientProperty("FlatLaf.styleClass", "large");
        nombreLabel.setForeground(Color.black);
        apellidoLabel.putClientProperty("FlatLaf.styleClass", "large");
        apellidoLabel.setForeground(Color.black);
        documentoLabel.putClientProperty("FlatLaf.styleClass", "large");
        documentoLabel.setForeground(Color.black);
        montoLabel.putClientProperty("FlatLaf.styleClass", "large");
        montoLabel.setForeground(Color.black);
        idPrestamoLabel.putClientProperty("FlatLaf.styleClass", "large");
        idPrestamoLabel.setForeground(Color.black);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        apellidoLabel = new javax.swing.JLabel();
        apellidoText = new javax.swing.JTextField();
        documentoLabel = new javax.swing.JLabel();
        documentoText = new javax.swing.JTextField();
        montoLabel = new javax.swing.JLabel();
        montoText = new javax.swing.JTextField();
        idPrestamoLabel = new javax.swing.JLabel();
        idPrestamoText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nombreLabel.setText("Nombre");

        apellidoLabel.setText("Apellido");

        documentoLabel.setText("Documento");

        montoLabel.setText("Monto");

        idPrestamoLabel.setText("ID Prestamo");

        jButton1.setBackground(new java.awt.Color(168, 48, 50));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Editar Prestamo");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellidoLabel)
                    .addComponent(apellidoText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentoLabel)
                    .addComponent(documentoText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idPrestamoLabel)
                    .addComponent(idPrestamoText)
                    .addComponent(montoLabel)
                    .addComponent(montoText)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(apellidoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(apellidoText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(montoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(montoText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(idPrestamoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(idPrestamoText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(documentoLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(documentoText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PrestamosController.editarPrestamo();
        nombreText.setText("");
        apellidoText.setText("");
        documentoText.setText("");
        montoText.setText("");
        idPrestamoText.setText("");
        PrincipalController.mostrarPrestamos();
        PrestamosController.mostrarPrestamos();
    }//GEN-LAST:event_jButton1ActionPerformed

    public JLabel getApellidoLabel() {
        return apellidoLabel;
    }

    public void setApellidoLabel(JLabel apellidoLabel) {
        this.apellidoLabel = apellidoLabel;
    }

    public JTextField getApellidoText() {
        return apellidoText;
    }

    public void setApellidoText(JTextField apellidoText) {
        this.apellidoText = apellidoText;
    }

    public JLabel getDocumentoLabel() {
        return documentoLabel;
    }

    public void setDocumentoLabel(JLabel documentoLabel) {
        this.documentoLabel = documentoLabel;
    }

    public JTextField getDocumentoText() {
        return documentoText;
    }

    public void setDocumentoText(JTextField documentoText) {
        this.documentoText = documentoText;
    }

    public JLabel getIdPrestamoLabel() {
        return idPrestamoLabel;
    }

    public void setIdPrestamoLabel(JLabel idPrestamoLabel) {
        this.idPrestamoLabel = idPrestamoLabel;
    }

    public JTextField getIdPrestamoText() {
        return idPrestamoText;
    }

    public void setIdPrestamoText(JTextField idPrestamoText) {
        this.idPrestamoText = idPrestamoText;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getMontoLabel() {
        return montoLabel;
    }

    public void setMontoLabel(JLabel montoLabel) {
        this.montoLabel = montoLabel;
    }

    public JTextField getMontoText() {
        return montoText;
    }

    public void setMontoText(JTextField montoText) {
        this.montoText = montoText;
    }

    public JLabel getNombreLabel() {
        return nombreLabel;
    }

    public void setNombreLabel(JLabel nombreLabel) {
        this.nombreLabel = nombreLabel;
    }

    public JTextField getNombreText() {
        return nombreText;
    }

    public void setNombreText(JTextField nombreText) {
        this.nombreText = nombreText;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JTextField apellidoText;
    private javax.swing.JLabel documentoLabel;
    private javax.swing.JTextField documentoText;
    private javax.swing.JLabel idPrestamoLabel;
    private javax.swing.JTextField idPrestamoText;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel montoLabel;
    private javax.swing.JTextField montoText;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreText;
    // End of variables declaration//GEN-END:variables
}
