/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.EmpleadosController;
import Controllers.PrincipalController;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author ivand
 */
public class RegistroEmpleadosView extends javax.swing.JPanel {

    /**
     * Creates new form EmpleadosView
     */
    public RegistroEmpleadosView() {
        initComponents();
        
        initStyle();
    }
    
    private void initStyle(){
        nombreLabel.putClientProperty("FlatLaf.styleClass", "large");
        nombreLabel.setForeground(Color.black);
        apellidoLabel.putClientProperty("FlatLaf.styleClass", "large");
        apellidoLabel.setForeground(Color.black);
        documentoLabel.putClientProperty("FlatLaf.styleClass", "large");
        documentoLabel.setForeground(Color.black);
        domicilioLabel.putClientProperty("FlatLaf.styleClass", "large");
        domicilioLabel.setForeground(Color.black);
        telefonoLabel.putClientProperty("FlatLaf.styleClass", "large");
        telefonoLabel.setForeground(Color.black);
        nombreText.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del empleado.");
        apellidoText.putClientProperty("JTextField.placeholderText", "Ingrese el apellido del empleado.");
        documentoText.putClientProperty("JTextField.placeholderText", "Ingrese el documento del empleado.");
        domicilioText.putClientProperty("JTextField.placeholderText", "Ingrese el domicilio del empleado.");
        telefonoText.putClientProperty("JTextField.placeholderText", "Ingrese el telefono del empleado.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        apellidoLabel = new javax.swing.JLabel();
        apellidoText = new javax.swing.JTextField();
        documentoLabel = new javax.swing.JLabel();
        documentoText = new javax.swing.JTextField();
        domicilioLabel = new javax.swing.JLabel();
        domicilioText = new javax.swing.JTextField();
        telefonoLabel = new javax.swing.JLabel();
        telefonoText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nombreLabel.setText("Nombre");

        apellidoLabel.setText("Apellido");

        apellidoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTextActionPerformed(evt);
            }
        });

        documentoLabel.setText("Documento");

        documentoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoTextActionPerformed(evt);
            }
        });

        domicilioLabel.setText("Domicilio");

        telefonoLabel.setText("Telefono");

        telefonoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTextActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(168, 48, 50));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar Empleado");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellidoLabel)
                    .addComponent(apellidoText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentoLabel)
                    .addComponent(documentoText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telefonoLabel)
                    .addComponent(telefonoText, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(domicilioLabel)
                    .addComponent(domicilioText, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(apellidoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(apellidoText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(domicilioLabel)
                        .addGap(18, 18, 18)
                        .addComponent(domicilioText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(telefonoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(documentoLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(documentoText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void apellidoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTextActionPerformed

    private void documentoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoTextActionPerformed

    private void telefonoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EmpleadosController.registrarEmpleados();
        nombreText.setText("");
        apellidoText.setText("");
        documentoText.setText("");
        domicilioText.setText("");
        telefonoText.setText("");
        PrincipalController.mostrarEmpleados();
        EmpleadosController.mostrarEmpleados();
    }//GEN-LAST:event_jButton1ActionPerformed

    public JLabel getApellidoLabel() {
        return apellidoLabel;
    }

    public void setApellidoLabel(JLabel apellidoLabel) {
        this.apellidoLabel = apellidoLabel;
    }

    public JTextField getApellidoText() {
        return apellidoText;
    }

    public void setApellidoText(JTextField apellidoText) {
        this.apellidoText = apellidoText;
    }

    public JLabel getDocumentoLabel() {
        return documentoLabel;
    }

    public void setDocumentoLabel(JLabel documentoLabel) {
        this.documentoLabel = documentoLabel;
    }

    public JTextField getDocumentoText() {
        return documentoText;
    }

    public void setDocumentoText(JTextField documentoText) {
        this.documentoText = documentoText;
    }

    public JLabel getDomicilioLabel() {
        return domicilioLabel;
    }

    public void setDomicilioLabel(JLabel domicilioLabel) {
        this.domicilioLabel = domicilioLabel;
    }

    public JTextField getDomicilioText() {
        return domicilioText;
    }

    public void setDomicilioText(JTextField domicilioText) {
        this.domicilioText = domicilioText;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getNombreLabel() {
        return nombreLabel;
    }

    public void setNombreLabel(JLabel nombreLabel) {
        this.nombreLabel = nombreLabel;
    }

    public JTextField getNombreText() {
        return nombreText;
    }

    public void setNombreText(JTextField nombreText) {
        this.nombreText = nombreText;
    }

    public JLabel getTelefonoLabel() {
        return telefonoLabel;
    }

    public void setTelefonoLabel(JLabel telefonoLabel) {
        this.telefonoLabel = telefonoLabel;
    }

    public JTextField getTelefonoText() {
        return telefonoText;
    }

    public void setTelefonoText(JTextField telefonoText) {
        this.telefonoText = telefonoText;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JTextField apellidoText;
    private javax.swing.JLabel documentoLabel;
    private javax.swing.JTextField documentoText;
    private javax.swing.JLabel domicilioLabel;
    private javax.swing.JTextField domicilioText;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField telefonoText;
    // End of variables declaration//GEN-END:variables
}
