/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controllers.PrincipalController;
import Controllers.StockController;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ivand
 */
public class RegistroStockView extends javax.swing.JPanel {

    /**
     * Creates new form RegistroStockView
     */
    public RegistroStockView() {
        initComponents();
        
        initStyle();
    }

    private void initStyle(){
        codigoLabel.putClientProperty("FlatLaf.styleClass", "large");
        codigoLabel.setForeground(Color.black);
        tipoLabel.putClientProperty("FlatLaf.styleClass", "large");
        tipoLabel.setForeground(Color.black);
        espesorLabel.putClientProperty("FlatLaf.styleClass", "large");
        espesorLabel.setForeground(Color.black);
        materialLabel.putClientProperty("FlatLaf.styleClass", "large");
        materialLabel.setForeground(Color.black);
        medidaLabel.putClientProperty("FlatLaf.styleClass", "large");
        medidaLabel.setForeground(Color.black);
        cantidadLabel.putClientProperty("FlatLaf.styleClass", "large");
        cantidadLabel.setForeground(Color.black);
        codigoText.putClientProperty("JTextField.placeholderText", "Ingrese el codigo del material.");
        espesorText.putClientProperty("JTextField.placeholderText", "Ingrese el espesor del material.");
        medidaText.putClientProperty("JTextField.placeholderText", "Ingrese la medida del material.");
        cantidadText.putClientProperty("JTextField.placeholderText", "Ingrese la cantidad de material.");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codigoLabel = new javax.swing.JLabel();
        codigoText = new javax.swing.JTextField();
        tipoLabel = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        espesorLabel = new javax.swing.JLabel();
        espesorText = new javax.swing.JTextField();
        materialLabel = new javax.swing.JLabel();
        materialComboBox = new javax.swing.JComboBox<>();
        medidaLabel = new javax.swing.JLabel();
        medidaText = new javax.swing.JTextField();
        cantidadLabel = new javax.swing.JLabel();
        cantidadText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        codigoLabel.setText("Codigo");

        tipoLabel.setText("Tipo");

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rectangular", "Circular", "Planchuela", "Angulo", "Barra" }));
        tipoComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        espesorLabel.setText("Espesor");

        materialLabel.setText("Material");

        materialComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hierro", "Acero" }));
        materialComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        medidaLabel.setText("Medida");

        cantidadLabel.setText("Cantidad");

        jButton1.setBackground(new java.awt.Color(168, 48, 50));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar Stock");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(espesorLabel)
                    .addComponent(espesorText)
                    .addComponent(tipoLabel)
                    .addComponent(codigoLabel)
                    .addComponent(codigoText)
                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantidadLabel)
                    .addComponent(cantidadText)
                    .addComponent(medidaLabel)
                    .addComponent(medidaText)
                    .addComponent(materialLabel)
                    .addComponent(materialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(materialLabel)
                        .addGap(18, 18, 18)
                        .addComponent(materialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(medidaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(medidaText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cantidadLabel)
                        .addGap(18, 18, 18)
                        .addComponent(cantidadText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codigoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tipoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(espesorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(espesorText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StockController.registrarStock();
        codigoText.setText("");
        espesorText.setText("");
        medidaText.setText("");
        cantidadText.setText("");
        PrincipalController.mostrarStock();
        StockController.mostrarStock();
    }//GEN-LAST:event_jButton1ActionPerformed

    public JLabel getCantidadLabel() {
        return cantidadLabel;
    }

    public void setCantidadLabel(JLabel cantidadLabel) {
        this.cantidadLabel = cantidadLabel;
    }

    public JTextField getCantidadText() {
        return cantidadText;
    }

    public void setCantidadText(JTextField cantidadText) {
        this.cantidadText = cantidadText;
    }

    public JLabel getCodigoLabel() {
        return codigoLabel;
    }

    public void setCodigoLabel(JLabel codigoLabel) {
        this.codigoLabel = codigoLabel;
    }

    public JTextField getCodigoText() {
        return codigoText;
    }

    public void setCodigoText(JTextField codigoText) {
        this.codigoText = codigoText;
    }

    public JLabel getEspesorLabel() {
        return espesorLabel;
    }

    public void setEspesorLabel(JLabel espesorLabel) {
        this.espesorLabel = espesorLabel;
    }

    public JTextField getEspesorText() {
        return espesorText;
    }

    public void setEspesorText(JTextField espesorText) {
        this.espesorText = espesorText;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JComboBox<String> getMaterialComboBox() {
        return materialComboBox;
    }

    public void setMaterialComboBox(JComboBox<String> materialComboBox) {
        this.materialComboBox = materialComboBox;
    }

    public JLabel getMaterialLabel() {
        return materialLabel;
    }

    public void setMaterialLabel(JLabel materialLabel) {
        this.materialLabel = materialLabel;
    }

    public JLabel getMedidaLabel() {
        return medidaLabel;
    }

    public void setMedidaLabel(JLabel medidaLabel) {
        this.medidaLabel = medidaLabel;
    }

    public JTextField getMedidaText() {
        return medidaText;
    }

    public void setMedidaText(JTextField medidaText) {
        this.medidaText = medidaText;
    }

    public JComboBox<String> getTipoComboBox() {
        return tipoComboBox;
    }

    public void setTipoComboBox(JComboBox<String> tipoComboBox) {
        this.tipoComboBox = tipoComboBox;
    }

    public JLabel getTipoLabel() {
        return tipoLabel;
    }

    public void setTipoLabel(JLabel tipoLabel) {
        this.tipoLabel = tipoLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JTextField cantidadText;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoText;
    private javax.swing.JLabel espesorLabel;
    private javax.swing.JTextField espesorText;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> materialComboBox;
    private javax.swing.JLabel materialLabel;
    private javax.swing.JLabel medidaLabel;
    private javax.swing.JTextField medidaText;
    private javax.swing.JComboBox<String> tipoComboBox;
    private javax.swing.JLabel tipoLabel;
    // End of variables declaration//GEN-END:variables
}
